version: '3.7'
services:
    react-nginx-app:
      stdin_open: true
      networks:
        - default
      build:
        context: .
        dockerfile: Dockerfile
      expose:
        - 443
      ports:
        - 443:443
      environment:
          - CHOKIDAR_USEPOLLING=true
networks:
  default:
    external: true
    name: host